export const pairs = [
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Понедельник',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Лабораторная',
		name: 'Проектирование человеко-машинного интерфейса',
		teacher: 'Тирских В.В.',
		classRoom: 'Д-503',
		group: 2
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Понедельник',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Практика',
		name: 'Основы управленческой деятельности',
		teacher: 'Кириллова Т.К.',
		classRoom: 'Д-521'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Понедельник',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Лабораторная',
		name: 'Архитектура ЭВМ',
		teacher: 'Кашковский В.В.',
		classRoom: 'Д-505',
		group: 1
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Вторник',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Практика',
		name: 'Общая физическая подготовка',
		teacher: 'Тирских В.В.',
		classRoom: 'Изумруд'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Вторник',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Практика',
		name: 'Математическая логика и теория алгоритмов',
		teacher: 'Кириллова Т.К.',
		classRoom: 'Г-212'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Вторник',
		date: '1 Сентября',
		timeStart: '13:50',
		timeEnd: '15:20',
		type: 'Лекция',
		name: 'Теория вероятностей и математическая статистика',
		teacher: 'Ширяева Н.К.',
		classRoom: 'Г-301'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Среда',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Лабораторная',
		name: 'Архитектура ЭВМ',
		teacher: 'Кашковский В.В.',
		classRoom: 'Д-503',
		group: 2
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Среда',
		date: '1 Сентября',
		timeStart: '13:50',
		timeEnd: '15:20',
		type: 'Практика',
		name: 'Русский язык и культура речи',
		teacher: 'Чебоненко О.С.',
		classRoom: 'Д-217'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Среда',
		date: '1 Сентября',
		timeStart: '15:30',
		timeEnd: '17:00',
		type: 'Лабораторная',
		name: 'Проектирование человеко-машинного интерфейса',
		teacher: 'Тирских В.В.',
		classRoom: 'А-516'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Четверг',
		date: '1 Сентября',
		timeStart: '08:30',
		timeEnd: '10:00',
		type: 'Лабораторная',
		name: 'Теория вероятностей и математическая статистика',
		teacher: 'Ширяева Н.К.',
		classRoom: 'Г-307',
		group: 1
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Четверг',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Практика',
		name: 'Философия',
		teacher: 'Яковлева Е.А.',
		classRoom: 'Д-723'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Четверг',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Лабораторная',
		name: 'Теория вероятностей и математическая статистика',
		teacher: 'Ширяева Н.К.',
		classRoom: 'Г-307',
		group: 2
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Пятница',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Лекция ',
		name: 'Проектирование человеко-машинного интерфейса',
		teacher: 'Тирских В.В.',
		classRoom: 'Д-413'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Пятница',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Лекция',
		name: 'Архитектура ЭВМ',
		teacher: 'Кашковский В.В.',
		classRoom: 'А-211'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Суббота',
		date: '1 Сентября',
		timeStart: '08:30',
		timeEnd: '10:00',
		type: 'Практика',
		name: 'Экономика',
		teacher: 'Журавлева О.В.',
		classRoom: 'Б-208'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Суббота',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Практика ',
		name: 'Экономика',
		teacher: 'Журавлева О.В.',
		classRoom: 'Б-208'
	},
	{
		typeWeek: 'Знаменатель',
		dayOfWeek: 'Суббота',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Лекция',
		name: 'Экономика',
		teacher: 'Журавлева О.В.',
		classRoom: 'Д-605'
	},

	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Понедельник',
		date: '1 Сентября',
		timeStart: '08:30',
		timeEnd: '10:00',
		type: 'Лабораторная',
		name: 'Проектирование человеко-машинного интерфейса',
		teacher: 'Тирских В.В.',
		classRoom: 'А-516',
		group: 1
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Понедельник',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Лекция',
		name: 'Основы управленческой деятельности',
		teacher: 'Кириллова Т.К.',
		classRoom: 'Г-121'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Понедельник',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Лабораторная',
		name: 'Основы управленческой деятельности',
		teacher: 'Кириллова Т.К.',
		classRoom: 'Д-521'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Понедельник',
		date: '1 Сентября',
		timeStart: '13:50',
		timeEnd: '15:20',
		type: 'Лабораторная',
		name: 'Архитектура ЭВМ',
		teacher: 'Кашковский В.В.',
		classRoom: 'Д-505',
		group: 2
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Вторник',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Практика',
		name: 'Теория вероятностей и математическая статистика',
		teacher: 'Ширяева Н.К.',
		classRoom: 'Г-212'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Вторник',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Практика',
		name: 'Математическая логика и теория алгоритмов',
		teacher: 'Розинова Н.С.',
		classRoom: 'Г-203'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Вторник',
		date: '1 Сентября',
		timeStart: '13:50',
		timeEnd: '15:30',
		type: 'Лекция',
		name: 'Теория вероятностей и математическая',
		teacher: 'Ширяева Н.К.',
		classRoom: 'Г-301'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Вторник',
		date: '1 Сентября',
		timeStart: '15:30',
		timeEnd: '17:00',
		type: 'Практика',
		name: 'Общая физическая подготовка',
		teacher: 'Гладышева А.А.',
		classRoom: 'Изумруд'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Среда',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Лабораторная',
		name: 'Архитектура ЭВМ',
		teacher: 'Кашковский В.В.',
		classRoom: 'А-513',
		group: 1
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Среда',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Лекция',
		name: 'Математическая логика и теория алгоритмов',
		teacher: 'Тирских В.В.',
		classRoom: 'Г-212'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Среда',
		date: '1 Сентября',
		timeStart: '13:50',
		timeEnd: '15:20',
		type: 'Лекция',
		name: 'Русский язык и культура речи',
		teacher: 'Чебоненко О.С.',
		classRoom: 'Д-617'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Четверг',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Практика',
		name: 'Философия',
		teacher: 'Яковлева Е.А.',
		classRoom: 'Д-723'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Четверг',
		date: '1 Сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Лекция',
		name: 'Философия',
		teacher: 'Яковлева Е.А.',
		classRoom: 'Д-605'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Четверг',
		date: '1 Сентября',
		timeStart: '13:50',
		timeEnd: '15:20',
		type: 'Лабораторная',
		name: 'Проектирование человеко-машинного интерфейса',
		teacher: 'Тирских В.В.',
		classRoom: 'А-509',
		group: 2
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Пятница',
		date: '1 Сентября',
		timeStart: '08:30',
		timeEnd: '10:00',
		type: 'Практика',
		name: 'Русский язык и культура речи',
		teacher: 'Чебоненко О.С.',
		classRoom: 'Д-723'
	},
	{
		typeWeek: 'Числитель',
		dayOfWeek: 'Пятница',
		date: '1 Сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Лекция',
		name: 'Проектирование человеко-машинного интерфейса',
		teacher: 'Тирских В.В.',
		classRoom: 'Д-413'
	}
];
