export const pairs = [
	{
		day: 'Понедельник, 1 сентября',
		timeStart: '08:30',
		timeEnd: '10:00',
		time: '08:30-10:00',
		type: 'Лабораторная',
		name: 'Программирование',
		teacher: 'Замятин В.М.',
		classRoom: 'Д-508',
		group: 1,
	},
	{
		day: 'Понедельник, 1 сентября',
		timeStart: '10:10',
		timeEnd: '11:40',
		type: 'Лекция',
		name: 'Программирование',
		teacher: 'Димов А.В.',
		classRoom: 'Д-521',
		group: 1,
	},
	{
		day: 'Понедельник, 1 сентября',
		timeStart: '12:10',
		timeEnd: '13:40',
		type: 'Практика',
		name: 'ООП',
		teacher: 'Молчанова Е.И.',
		classRoom: 'Д-518',
		group: 1,
	},
	{
		day: 'Понедельник, 1 сентября',
		timeStart: '13:50',
		timeEnd: '15:20',
		type: 'Лабораторная',
		name: 'ООП',
		teacher: 'Молчанова Е.И.',
		classRoom: 'Д-501',
		group: 2,
	},
	{
		day: 'Понедельник, 1 сентября',
		timeStart: '15:30',
		timeEnd: '17:00',
		type: 'Лабораторная',
		name: 'Программирование',
		classRoom: 'Д-508',
		teacher: 'Замятин В.М.',
		group: 2,
	},
	{
		day: 'Понедельник, 1 сентября',
		timeStart: '17:10',
		timeEnd: '18:40',
		type: 'Практика',
		name: 'ООП',
		teacher: 'Молчанова Е.И.',
		classRoom: 'Д-501',
		group: 2,
	},
];
